language: ruby
cache:
- bundle
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
deploy:
  provider: heroku
  api_key:
    secure: KZAA19hGsqZ8V+i4JkZQOMip6t7whYTCXlOTDLIaScKH6DOEHxeNocohn2372IgN/QPa14SSBSMo5xlIZX+ZHgxOVNwHARYwFEhwSG2wtrcIrV4rIN9w9ccuwwe8tfixM8Hqbd1zFjQuELJ7j/iTo1STIPSNQRwUN0NWVEPBAFzzqhkDuFBwOsYRnoC4j71b09inFEvlDVEAX4DgQbWDooZX/7DUtbHy1ugmUZXY0/HpOJpVrbfPBfWK4PQE5C/kKBe+MVYPxDhznwxrxpu4yAwSP0VRCXbm6bEqiExRMgcu0/bX/EKL0Eca0HhjXW6iG4VVQtps/ba4cTpumCVG4zNTRjyev2k5WnjTaRVrPOvccCAy6c7pRYClCOnpPsvAKP4kZw1SYDRvWzZ7Hn3UNzZpGmMFbua4Ym7YODdnyF84Innxw7AqH0f5tFApV4lejzLRPfVgD7vnS2/ujXQ/3wH7zUuJ+gvQ35mRtSFht4lXCU6Hbs//DFcF4vwJskp+cSAs/vp+6QCZCNFbHVgFXHITSi9d+Z4MyEIVRUbDLHltJldMAOfI+uvjENO5CQviRoFBjQeskQE05b8gU7TkRfjBYNG/fP6COtezYz1Chb2ijyVembyrC2oDGQ7N2R8club7R6jaussv2aiqfrVtu6I5V8hTKXo1bAJmIwfCe5Y=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
