language: ruby
cache:
- bundler
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
deploy:
  provider: heroku
  api_key:
    secure: g3zlaMGS7KARKfnskvd6W0BqJq5+w0gWhicP7f8AKfhhphr8haNP0xo2ElwE3I0MKEyHHcQloWfSIdwAMWuMOpjq+LHzmo61HvQq9EynMo3JzMZcgKOPK89YyQSttuVJ/7oIt1ri/v1+QgqHDWa2LMtyIj33G1y0JZWGcyQWUq2KtBtenG9VA+IYonvIEgA6moYN/xiwDR1PuUiDEvQQKjT/O0sx7KTeOUk37hcedGOcTjdHJbp6hgKSOr4ERXZOnV1Gzn9wGTXoT1n62ZGBZ7FfwO30ctbjgv16aYZ8x/mWrMArT+Cu68WCR24nJAFl9BARJFtP5CouzG7mGXKZmKrjEfBlWovJGAPZBd4rbeQHarlzoyFrOkTO6p0W+GNtn6lznLI0cSeO/8MxLfHSdYPx2zJtVmvZI3CaoyCAw6p65/TDesfmXVwRoPKjo2f05hrAPLfP7fSd1V72P9C+QJhzw9gHiDxoeWDJq5GOqGodhtDGYVDy6gtKnEhbAzP0bsHlOOsoEEbvYRiIwMeK5NrxUZf/xw7SaRlv+4ka/QqDc9iONWkWR+nGBdOJCc9zS46ie7SxAH+C0xj/i/zdiHzzXINvtEEu3tFfzTv+GODuc59qlfuOihhhNhaWbZcBoxwjJL7Ja88VRy8WgAyozgCUKWBBOLF+G4APlZLzO/A=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
