language: ruby
cache:
  directories:
  - vendor/bundle
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: pl4vV4EoovYjtrwSlsZF1pfpsdAa2Ehl7Gc1ipJI5mnbcxstH22jTIyMAfYoV+WLj5ffy/Ji0VROVIrmec1KzGxb0YKRvth3R7WoHs9f7wBzVgwWpYkuqE5rEcaAr+cUy9E+oLtkb6Ueg1UZDrkPymYhPltz8ZvpNMQducfpCHWdRZVIjnEwj1MiUjA1BZv8kXTjM94rFI+XMH/MeEqNVIj+KEVXZHRwm0oXxJf0PivvZ3+fWOSFCUk0UVg2d5gVM/bEZSAuCdjMRqhnRwkdEzws426ucXmpQkDVkEtZGbtphg8jnpsec/dvnj3xkgS8GvcBe7VZgPBLIAz7heYtA/lN/Xlvagyy3JCd1GQ8MXd62cMz3dprfBwoxC7ptgvK+XmaAoFHoQn2omORrdNeP6JTTRREA+fWRPt/EIIV2vnek7xqRljQ4w9cdZyo/4AGaYGiaaATpGqsZ35bNkZvGnyaZxtok+oUNnTiu9RuYqVaqXB0xnN6kionn+6DomHyvkak0NoHPDhsoxc9ra/HGHMuaulxp8F5dQnULLGcYvaz15jYWjs/+dXfOhvw7ds/5aJzGuzQqTFFwKXZkj1u9VoMQetNIF1np87QJIaDKlqqR9yWK0OOBNZ4AMRy5CRuWzMLniCATWJFJW1WGsScrm/4wr+J8NxTiKZJDTm/Xb0=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
