language: ruby
cache:
- bundle
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
install:
- bundle install 
deploy:
  provider: heroku
  api_key:
    secure: tNMMT7ohIIg6uURTxV4+TiX1cbSpJpBmlGlkqmeSa5H91pmSHK6aYbsTgvjrgm07zo4gdJcQIZVar32cVcHBEIkuwmpsVA47j4Zk50Oc5jcoiH4oe3mhS4QeWNPFKlCB28p1rfKDRoA4Ju8yznR2t8zLZQmkSEYqsCMngyqubgeFyvwWDJZ8SyEowQaKbE+rq1+1cnhQBy/2Nb06mOsckKyQ9rMF3OlQewherY+vEWfbz4cU7EiPmHv+nmqIc1ifROLgpwuHTuM7wy+tg0/WdfG6dQTi7P/HuuA48f8lw8Jsu5gmVZYtZgUJPy1j65IaN1aKUCxhKIKrsxX1zCkgvP6o83Ohaffvonm6Y0b2ptZPY5gsT9zQCLm2EoZiCX09XYlIy4f5hl0QM8xz1S9OIZagaY2ui5DEOAjggWssTBLxPUJXBp7qpUuLmFboCrxRNeKQP6t6R3d/DL6cHYIThVaMEQc60MFljjifdjQLLW/ngel6wLBtvJP2cxMFqP6lOVox8rq0f0lyXsfqdnaFZFqjmztAD25zxQ6HGjoOmABMd9WRMU6roIC/VW0NQq664WRRmT7FItPGp1dOmC/YQcc8krOIniHPGZV3DxmP+MorVgC+/2WHWg8ueOx3rC51J3iIREDi0SCJ9gU23vRQ4HuFgsEPQ6rYScj5DD5FpO0=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
