language: ruby
cache:
- bundler
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
deploy:
  provider: heroku
  api_key:
    secure: ndHWsHimT4Q8zNRkKmvciA5zasdIpD9wnnh68OiGoB/ufGqQFx6d5vAqcdARBOgz8kdGZuMVGGPUNOZMAXI9ScUumfyys8b29THQpQ28t0ppbuo0eTZZuPtor+aQwVy6V0FJpyeaoXGX5e6WfW9KxKgjQKsAvd74siVU5F5RxjS0/3TKzeucCbAHcgVtBaR2xMCGj8Er77R4/V1H8O27wwYLntVEmCZq1xOYIVGoNBb7iRb7E7TMYZqWfIRoKDuEeSG4m6yIWkxAjfvc6/Ac1Jxs5+7GhLImdE29jlH+mSaEuc1ET9mZxM4rnmv8oy97mn0RzfvdN9rHDnQjaqRVMe7rmZRktyU590m6PPZA85XSkgMXHuJ/f+OcNFTybkqZwySVIcA6ImJV+x29owct4ID2osLWW3hZT3URfFx9lveSz/D35GHhvMBAJrWsOsjYFsIAHCX6gx9/WQUZ0gUesF7w5wAw+BjzA9AjJwWEmofc/1SPk7+KQKAA7d1vv7bqUZD9Ps+aa2rkMtuf66I2rsvBQnf0Nl1XdPkFfUbEQl5u03ZIAZOjU7WoBJZ3+xKWZZgGpXVuEkIMF4tLpIXeR3tt45QxI8P6e9aS6GAGSXxS4LEKpW4I0pan6a1dLTaAMHjb7/wQnqC98T3/RzlzonfHLuo7rl4c/GvB5U1JBp8=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
