language: ruby
cache:
- bundle
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --deployment
deploy:
  provider: heroku
  api_key:
    secure: m9CPotxmmxNv9kLjp7kIx7FaeKM7GaMJl/G4pQnsPBm+1ilnFwPq6PinupoQXmH7VoDQPFct9OGy96F38LPQDyQGewm/cMGF6P+5WhiOVtJZTlieijEHxsTP5sJ61fdy3/SiFhVXT7LAdAIm/4XKxKwtgdQVygF1As1wpbl9T6hIzCQ6pPH2nNWA/eWuWwQIyOv03SmOb9s/U3dX3CRxVWZD2PETioj2ousdjnD5kve7cKMf/fZxMPLKnT7Pg8/vbswMF6fuL9SVpeEfBL98+s5Z5pnCaxi/bZdE0GlpmW/GuQt9Ih9Vfp0g/ULMB/dhgtBoOghe8BGAXkOmBgHfXcbKY55NRaQlFQYP+5Ozheu+XQBN2gh8Gwue8jnTg5a2VFokPDMotOt3OPMlj2nKIIezjLVDwBB75KU1AaUJCcx1L5VlNK4SeUTmG+6K+uLosZbeo4HOJLubk1xWHgDM+k9fM0spkw9elVHOehGvpIVk+y7Ky2j63Ffq+AbEGDF1Tb3tTGV0A4n0H7uSJc4vloHiKrA3D0ppVfYAtDVg6527ifwHnPudjrAqLtrxMWRfMFRT+lWETn5QDbp32bFvi4q4GCXfWIEBMf83+2kCix1lm0f+Qfjf1lv1pVHPF/qp4m6cInsCX9WHFQ2ndszn4GA9ViTqkGIg1NhMJ2v+MVo=
  app: meet-andeat
  on:
    repo: AsadK47/Meet-and-Eat
  skip_cleanup: true
